"""Common structural interface for the manually implemented MCP transports."""

from typing import Any, Mapping, Protocol


class McpClient(Protocol):
    def connect(self) -> Any: ...
    def list_tools(self) -> list[dict[str, Any]]: ...
    def call_tool(self, name: str, arguments: Mapping[str, Any] | None = None) -> Any: ...
    def close(self) -> None: ...
